export enum BACKEND_ENDPOINTS {
    REGISTER_ADMIN = "api/auth/register/local/admin",
    REGISTER_USER = "api/auth/register/local/user",
    LOGIN = "api/auth/login",
    FORGOT_PASSWORD = "api/auth/forgot-password",
    VERIFY_RESET_TOKEN = "api/auth/verify-reset-token",
    CHANGE_PASSWORD = "api/auth/change-password",
    ACTIVATE_ACCOUNT = "api/auth/activate-account",
    GET_ROL = "api/roles/",
    CREATE_ROL = "api/roles/create",
    UPDATE_ROL = "api/roles/update",
    DELETE_ROL = "api/roles",
    GET_BUSINESSES = "api/businesses", 
    GET_USERS = "api/users",
    UPDATE_USERS = "api/users",
    DELETE_USERS_WITH_SCHEDULE = "api/users/deleteUserWithSchedule",
    DELETE_USERS = "api/users",
    BLOCKED_USERS ="api/users/blocked",
    LIST_FLEET = "api/fleet",
    CREATE_FLEET = "api/fleet/create",
    DELETE_FLEET = "api/fleet",
    UPDATE_FLEET = "api/fleet",
    CREATE_SCHEDULE = "api/schedule/create",
    GET_SCHEDULE = "api/schedule",
    DELETE_SCHEDULE = "api/schedule",
    UPDATE_SCHEDULE = "api/schedule",
    DELETE_WITH_DOCUMENT_FLEET = "api/fleet/deleteWithDocuments",
    CREATE_TARIFF = "api/tariff/create",
    GET_TARIFF = "api/tariff",
    UPDATE_TARIFF = "api/tariff",
    DELETE_TARIFF = "api/tariff",
    CREATE_CLIENT = "api/client/create",
    GET_CLIENT = "api/client",
    UPDATE_CLIENT = "api/client",
    DELETE_CLIENT = "api/client",
    BLOCKED_CLIENT = "",
    DELETE_WITH_VESSEL_CLIENT = "api/client/deleteWithVeseel",
    CREATE_MANEUVER = "api/maneuver/create",
    UPDATE_MANEUVER = "api/maneuver",
    DELETE_MANEUVER = "api/maneuver",
    GET_MANEUVER = "api/maneuver",
    GET_COUNTRY = "api/country",
    GET_CMUNICIPALITY = "api/municipality",
    GET_CMUNICIPALIT_COUNTRY  = "api/municipality/country",
    GET_VESSEL_BY_CLIENT  = "api/vessel/by-client",
    GET_VESSEL = "api/vessel",
    UPDATE_VESSEL = "api/vessel",
    GET_VESSEL_BY_ID = "api/vessel",
    DELETE_VESSEL = "api/vessel",
    CREATE_EQUIPMENT = "api/equipment/create",
    GET_EQUIPMENT = "api/equipment",
    UPDATE_EQUIPMENT = "api/equipment",
    DELETE_EQUIPMENT = "api/equipment",
    GET_LIST_DOCUMENT = "api/list-document",
    LIST_FLEET_DOCUMENT = "api/fleet/document-expire",





  }